app:
  # Logging level for the application | type=str | choices=['DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL']
  log_level: INFO
calendar:
  # Number of collages to be generated (e.g. number of weeks) | type=int
  collagesToGenerate: 5
  # Country/state codes for public holidays, e.g., NY,CA | type=str
  holidayCountries: SN
  # Language for the calendar (e.g., de_DE, en_US) | type=str
  language: de_DE
  # Start date of the calendar | type=datetime [CLI]
  startDate: '2025-12-29T00:00:00'
  # True: Calendar elements are generated | type=bool | choices=[True, False]
  useCalendar: true
general:
  # Path to anniversaries.ini file (absolute, or relative to this config.ini file) | type=PosixPath
  anniversariesConfig: anniversaries.ini
  # This is the title of the composition on the first page. Leave empty if not required. | type=str
  compositionTitle: This is the title of the composition
  # Path to locations.ini file (absolute, or relative to this config.ini file) | type=PosixPath
  locationsConfig: locations_en.ini
  # Path to the directory containing photos (absolute, or relative to this config.ini file) | type=PosixPath [CLI]
  photoDirectory: images
geo:
  # Minimum range for map display (degrees) | type=int
  minimalExtension: 7
  # Use GPS data to generate maps | type=bool | choices=[True, False]
  usePhotoLocationMaps: true
layout:
  # Combine all generated collages into one pdf | type=bool | choices=[True, False]
  generatePdf: true
  # Bottom margin in mm | type=int
  marginBottom: 3
  # Side margins in mm | type=int
  marginSides: 3
  # Top margin in mm | type=int
  marginTop: 6
  # Spacing between elements in mm | type=int
  spacing: 2
  # Include photo descriptions in the collage | type=bool | choices=[True, False]
  usePhotoDescription: true
  # Use short weekday names (e.g., Mon, Tue) | type=bool | choices=[True, False]
  useShortDayNames: false
  # Use short month names (e.g., Jan, Feb) | type=bool | choices=[True, False]
  useShortMonthNames: true
size:
  # Height of the calendar area in mm | type=int
  calendarHeight: 18
  # Resolution of the image in dpi | type=int [CLI]
  dpi: 150
  # Height of the collage in mm | type=int [CLI]
  height: 154
  # JPG compression quality (1-100) | type=int
  jpgQuality: 90
  # Height of the locations map in mm | type=int
  mapHeight: 20
  # Width of the locations map in mm | type=int
  mapWidth: 20
  # Width of the collage in mm | type=int [CLI]
  width: 216
style:
  # Background color (RGB) | type=Color
  backgroundColor: '#141414'
  # Font size for anniversaries: Text with anniversaries and holiday names | type=Font
  fontAnniversaries:
  - DejaVuSans.ttf
  - 5
  - '#ff0000'
  # Font for the description texts | type=Font
  fontDescription:
  - DejaVuSans.ttf
  - 6
  - '#ffffff'
  # Font size for large text like the title and the weekday numbers | type=Font
  fontLarge:
  - DejaVuSans.ttf
  - 10
  - '#ffffff'
  # Font size for small text like the weekday names | type=Font
  fontSmall:
  - DejaVuSans.ttf
  - 6
  - '#969696'